# Generated by Django 4.2.6 on 2023-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=200)),
                ('categoryimage', models.ImageField(default='null.jpg', upload_to='images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=300)),
                ('productcategory', models.CharField(max_length=200)),
                ('productimage', models.ImageField(default='null.jpg', upload_to='images')),
                ('productprice', models.IntegerField()),
            ],
        ),
    ]
