# Generated by Django 4.2.6 on 2023-11-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_replay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Replay',
        ),
    ]
