# Generated by Django 4.2.6 on 2023-11-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_remove_complaint_productid_complaint_cartid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cartid',
        ),
        migrations.AddField(
            model_name='complaint',
            name='compid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.checkout'),
        ),
    ]
