# Generated by Django 4.2.6 on 2023-11-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_remove_complaint_cartid_complaint_compid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
