# Generated by Django 4.2.6 on 2023-11-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.register'),
        ),
    ]
